[local]
localhost

[mongodb]
mongodb.daws90s.sbs

[redis]
redis.daws90s.sbs

[mysql]
mysql.daws90s.sbs

[rabbitmq]
rabbitmq.daws90s.sbs

[catalogue]
catalogue.daws90s.sbs

[user]
user.daws90s.sbs

[cart]
cart.daws90s.sbs

[shipping]
shipping.daws90s.sbs

[payment]
payment.daws90s.sbs

[frontend]
frontend.daws90s.sbs